// <auto-generated />
using System;
using DeliveryDemo.Infrastructure.Warehouse;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeliveryDemo.Infrastructure.Warehouse.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    partial class WarehouseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeliveryDemo.Domain.Warehouse.Goods", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("goods", null, t =>
                        {
                            t.HasCheckConstraint("ck_goods_text", "btrim(code) <> '' AND btrim(name) <> ''");
                        });
                });

            modelBuilder.Entity("DeliveryDemo.Domain.Warehouse.InventoryBalance", b =>
                {
                    b.Property<Guid>("GoodsId")
                        .HasColumnType("uuid")
                        .HasColumnName("goods_id");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("GoodsId", "WarehouseId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("inventory_balances", null, t =>
                        {
                            t.HasCheckConstraint("ck_balance_quantity", "quantity >= 0 AND quantity < 100000000000000");
                        });
                });

            modelBuilder.Entity("DeliveryDemo.Domain.Warehouse.StockTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GoodsId")
                        .HasColumnType("uuid")
                        .HasColumnName("goods_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("quantity");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId", "OccurredAt");

                    b.HasIndex("GoodsId", "WarehouseId", "OccurredAt");

                    b.ToTable("stock_transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_transaction_actor", "btrim(actor) <> ''");

                            t.HasCheckConstraint("ck_transaction_quantity", "quantity > 0 AND quantity < 100000000000000");

                            t.HasCheckConstraint("ck_transaction_type", "type IN (1, 2)");
                        });
                });

            modelBuilder.Entity("DeliveryDemo.Domain.Warehouse.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("warehouses", null, t =>
                        {
                            t.HasCheckConstraint("ck_warehouses_text", "btrim(code) <> '' AND btrim(name) <> ''");
                        });
                });

            modelBuilder.Entity("DeliveryDemo.Domain.Warehouse.InventoryBalance", b =>
                {
                    b.HasOne("DeliveryDemo.Domain.Warehouse.Goods", null)
                        .WithMany()
                        .HasForeignKey("GoodsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliveryDemo.Domain.Warehouse.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DeliveryDemo.Domain.Warehouse.StockTransaction", b =>
                {
                    b.HasOne("DeliveryDemo.Domain.Warehouse.Goods", null)
                        .WithMany()
                        .HasForeignKey("GoodsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliveryDemo.Domain.Warehouse.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
