import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, expect, test, vi } from 'vitest'
import { Catalog } from './Catalog'
import App from './App'

const item: { id: string, code: string, name: string, archivedAt: string | null } = { id: 'master-id', code: 'A01', name: 'Mặt hàng A', archivedAt: null }
const list = (items = [item], total = items.length) => ({ items, total, page: 1, pageSize: 20 })
const ok = (body: unknown) => ({ ok: true, json: async () => body })
afterEach(() => { cleanup(); vi.unstubAllGlobals(); window.location.hash = '' })

test.each(['goods', 'warehouses'] as const)('%s supports validation, create, duplicate-submit protection and refresh', async kind => {
  let finish!: (value: unknown) => void
  const fetch = vi.fn().mockResolvedValueOnce(ok(list([]))).mockImplementationOnce(() => new Promise(resolve => { finish = resolve })).mockResolvedValueOnce(ok(list()))
  vi.stubGlobal('fetch', fetch)
  render(<Catalog kind={kind} />)
  expect(await screen.findByText(/Không có/)).toBeInTheDocument()
  fireEvent.click(screen.getByText(kind === 'goods' ? 'Tạo hàng hóa' : 'Tạo kho'))
  fireEvent.click(screen.getByText('Lưu'))
  expect(screen.getByLabelText('Mã')).toHaveAttribute('aria-invalid', 'true')
  expect(screen.getByLabelText('Tên')).toHaveAttribute('aria-invalid', 'true')
  expect(fetch).toHaveBeenCalledTimes(1)
  fireEvent.change(screen.getByLabelText('Mã'), { target: { value: ' A01 ' } })
  fireEvent.change(screen.getByLabelText('Tên'), { target: { value: ' Mặt hàng A ' } })
  fireEvent.click(screen.getByText('Lưu'))
  expect(screen.getByText('Đang lưu…')).toBeDisabled()
  fireEvent.submit(screen.getByRole('form', { name: kind === 'goods' ? 'Tạo hàng hóa' : 'Tạo kho' }))
  expect(fetch).toHaveBeenCalledTimes(2)
  expect(fetch.mock.calls[1][0]).toBe(`/api/${kind}`)
  expect(fetch.mock.calls[1][1]).toMatchObject({ method: 'POST', body: JSON.stringify({ code: 'A01', name: 'Mặt hàng A' }) })
  await act(async () => finish(ok(item)))
  expect(await screen.findByText('Đã lưu thành công.')).toBeInTheDocument()
  expect(await screen.findByText('Mặt hàng A')).toBeInTheDocument()
  expect(screen.queryByLabelText('Mã')).not.toBeInTheDocument()
})

test.each(['goods', 'warehouses'] as const)('%s updates names with immutable codes and shows API errors', async kind => {
  const fetch = vi.fn().mockResolvedValueOnce(ok(list())).mockResolvedValueOnce({ ok: false, json: async () => ({ title: 'Validation failed', errors: { name: ['API name error'] } }) }).mockResolvedValueOnce({ ok: false, json: async () => ({ title: 'Catalog conflict' }) }).mockResolvedValueOnce(ok({ ...item, name: 'Tên mới' })).mockResolvedValueOnce(ok(list([{ ...item, name: 'Tên mới' }])))
  vi.stubGlobal('fetch', fetch)
  render(<Catalog kind={kind} />)
  fireEvent.click(await screen.findByRole('button', { name: 'Sửa A01' }))
  expect(screen.getByLabelText('Mã')).toHaveAttribute('readonly')
  expect(screen.getByLabelText('Tên')).toHaveFocus()
  fireEvent.change(screen.getByLabelText('Tên'), { target: { value: 'Tên mới' } })
  fireEvent.click(screen.getByText('Lưu'))
  expect(await screen.findByText('API name error')).toBeInTheDocument()
  expect(screen.getByLabelText('Tên')).toHaveAttribute('aria-invalid', 'true')
  fireEvent.click(screen.getByText('Lưu'))
  expect(await screen.findByText('Catalog conflict')).toBeInTheDocument()
  fireEvent.click(screen.getByText('Lưu'))
  expect(await screen.findByText('Đã lưu thành công.')).toBeInTheDocument()
  expect(await screen.findByText('Tên mới')).toBeInTheDocument()
  expect(fetch.mock.calls[1][0]).toBe(`/api/${kind}/master-id`)
  expect(fetch.mock.calls[1][1].method).toBe('PUT')
})

test('list shows loading/error/retry and submits search, archive filters and pagination', async () => {
  const fetch = vi.fn().mockRejectedValueOnce(new Error('Network unavailable')).mockResolvedValue(ok(list([item], 21)))
  vi.stubGlobal('fetch', fetch)
  render(<Catalog kind="goods" />)
  expect(screen.getByText('Đang tải danh sách…')).toBeInTheDocument()
  expect(await screen.findByText('Network unavailable')).toBeInTheDocument()
  fireEvent.click(screen.getByText('Thử lại'))
  await screen.findByText(item.name)
  fireEvent.click(screen.getByText('Trang sau'))
  await waitFor(() => expect(fetch.mock.calls.at(-1)?.[0]).toContain('page=2'))
  await screen.findByText(item.name)
  fireEvent.change(screen.getByLabelText('Tìm theo mã hoặc tên'), { target: { value: 'A01' } })
  fireEvent.click(screen.getByText('Tìm kiếm'))
  await waitFor(() => expect(fetch.mock.calls.at(-1)?.[0]).toContain('page=1&pageSize=20&search=A01&archived=false'))
  fireEvent.change(screen.getByLabelText('Trạng thái'), { target: { value: 'true' } })
  await waitFor(() => expect(fetch.mock.calls.at(-1)?.[0]).toContain('archived=true'))
  fireEvent.change(screen.getByLabelText('Trạng thái'), { target: { value: '' } })
  await waitFor(() => expect(fetch.mock.calls.at(-1)?.[0]).not.toContain('archived='))
})

test('archived items are read-only and stale list requests are aborted', async () => {
  const archived = { ...item, archivedAt: '2026-10-05' }
  const fetch = vi.fn().mockResolvedValue(ok(list([archived])))
  vi.stubGlobal('fetch', fetch)
  const view = render(<Catalog kind="goods" />)
  await screen.findByText(item.name)
  expect(screen.queryByRole('button', { name: 'Sửa A01' })).not.toBeInTheDocument()
  view.unmount()
  expect(fetch.mock.calls[0][1].signal.aborted).toBe(true)
})

test('length boundaries prevent invalid requests and cancel returns focus', async () => {
  const fetch = vi.fn().mockResolvedValue(ok(list([])))
  vi.stubGlobal('fetch', fetch)
  render(<Catalog kind="goods" />)
  await screen.findByText(/Không có/)
  fireEvent.click(screen.getByText('Tạo hàng hóa'))
  expect(screen.getByLabelText('Mã')).toHaveFocus()
  fireEvent.change(screen.getByLabelText('Mã'), { target: { value: 'A'.repeat(65) } })
  fireEvent.change(screen.getByLabelText('Tên'), { target: { value: 'N'.repeat(257) } })
  fireEvent.click(screen.getByText('Lưu'))
  expect(screen.getByLabelText('Mã')).toHaveAttribute('aria-invalid', 'true')
  expect(screen.getByLabelText('Tên')).toHaveAttribute('aria-invalid', 'true')
  expect(fetch).toHaveBeenCalledTimes(1)
  fireEvent.click(screen.getByText('Hủy'))
  expect(screen.getByText('Tạo hàng hóa')).toHaveFocus()
})

test('hash routes, menu and home modules stay integrated', async () => {
  vi.stubGlobal('fetch', vi.fn().mockImplementation((path: string) => Promise.resolve(ok(path === '/api/health' ? { status: 'Healthy' } : list([])))))
  window.location.hash = '#/goods'
  render(<App />)
  expect(await screen.findByText('Danh sách hàng hóa')).toBeInTheDocument()
  await act(async () => { window.location.hash = '#/warehouses'; window.dispatchEvent(new HashChangeEvent('hashchange')) })
  expect(await screen.findByText('Danh sách kho')).toBeInTheDocument()
  expect(screen.getByRole('link', { name: 'Kho' })).toHaveAttribute('aria-current', 'page')
  await act(async () => { window.location.hash = '#/'; window.dispatchEvent(new HashChangeEvent('hashchange')) })
  expect(await screen.findByText('Nhập và xuất kho')).toBeInTheDocument()
  expect(screen.getByRole('link', { name: 'Quản lý hàng hóa' })).toHaveAttribute('href', '#/goods')
})
